### ISSUE TITLE
Type String in Headers KayValuePair (ApiResponse)

### ISSUE THREAD

**Issue by TechosRX** [Jimmy062006/ESIClient.Dotcore#1]
the KeyValuePair Value from ApiResponse Header containt only the Types as String
![Screenshot](https://user-images.githubusercontent.com/6439501/41098097-8a74c65e-6a5a-11e8-911d-08045605fb2e.png)

**Comment by Jimmy062006** [comment]
Also as a note I have updated the Swagger language file so that it automatically makes this change from now on 0.8.3 should be up soon provided it compiles.
